<?xml version="1.0" encoding="utf-8"?><Database Name="OrderDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=XZJS-PC\SQLEXPRESS;Initial Catalog=OrderDB;Persist Security Info=True;User ID=sa" SettingsObjectName="OrderMenu.Properties.Settings" SettingsPropertyName="OrderDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Desk" Member="Desk">
    <Type Name="Desk">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Desk_DeskMenu" Member="DeskMenu" ThisKey="ID" OtherKey="DeskID" Type="DeskMenu" />
      <Association Name="Desk_OrderDesk" Member="OrderDesk" ThisKey="ID" OtherKey="DeskID" Type="OrderDesk" />
      <Association Name="Room_Desk" Member="Room" ThisKey="RoomID" OtherKey="ID" Type="Room" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Worker_Desk" Member="Worker" ThisKey="WorkID" OtherKey="ID" Type="Worker" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.WorkerMenu" Member="WorkerMenu">
    <Type Name="WorkerMenu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_WorkerMenu" Member="Menu" ThisKey="MenuID" OtherKey="ID" Type="Menu" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Worker_WorkerMenu" Member="Worker" ThisKey="WorkerID" OtherKey="ID" Type="Worker" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.DeskMenu" Member="DeskMenu">
    <Type Name="DeskMenu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeskID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CookID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CookStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Desk_DeskMenu" Member="Desk" ThisKey="DeskID" OtherKey="ID" Type="Desk" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Menu_DeskMenu" Member="Menu" ThisKey="MenuID" OtherKey="ID" Type="Menu" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Worker_DeskMenu" Member="Worker" ThisKey="CookID" OtherKey="ID" Type="Worker" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menu">
    <Type Name="Menu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Menu_WorkerMenu" Member="WorkerMenu" ThisKey="ID" OtherKey="MenuID" Type="WorkerMenu" />
      <Association Name="Menu_DeskMenu" Member="DeskMenu" ThisKey="ID" OtherKey="MenuID" Type="DeskMenu" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDesk" Member="OrderDesk">
    <Type Name="OrderDesk">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeskID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClientPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Desk_OrderDesk" Member="Desk" ThisKey="DeskID" OtherKey="ID" Type="Desk" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Room">
    <Type Name="Room">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Specification" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Room_Desk" Member="Desk" ThisKey="ID" OtherKey="RoomID" Type="Desk" />
    </Type>
  </Table>
  <Table Name="dbo.Worker" Member="Worker">
    <Type Name="Worker">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Profession" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pwd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Worker_Desk" Member="Desk" ThisKey="ID" OtherKey="WorkID" Type="Desk" />
      <Association Name="Worker_WorkerMenu" Member="WorkerMenu" ThisKey="ID" OtherKey="WorkerID" Type="WorkerMenu" />
      <Association Name="Worker_DeskMenu" Member="DeskMenu" ThisKey="ID" OtherKey="CookID" Type="DeskMenu" />
    </Type>
  </Table>
</Database>